# Generated by Django 4.2.23 on 2026-03-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='currency',
            field=models.CharField(choices=[('UZS', 'Сум'), ('USD', 'Доллар')], default='UZS', max_length=3),
        ),
        migrations.AlterField(
            model_name='debt',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='debt',
            name='date',
            field=models.DateField(),
        ),
    ]
