# Generated by Django 4.2.23 on 2026-04-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_debt_currency_alter_debt_amount_alter_debt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина'),
        ),
    ]
