# Generated by Django 4.2.23 on 2026-04-17 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_debt_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.debtor'),
        ),
    ]
