# Generated by Django 4.2.23 on 2026-04-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_debt_debtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
