# Generated by Django 4.2.23 on 2026-04-20 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_debt_reason_alter_debtor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.debtor'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Имя должника'),
        ),
    ]
