# Generated by Django 4.2.23 on 2026-04-20 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_debt_debtor_alter_debt_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='api.debtor'),
        ),
    ]
